### ISSUE TITLE
Chrome Driver isn't working

### ISSUE THREAD

**Issue by iSkyNavy** [usil/selenium-nodejs-starter#8]
-- Dependencies related to chrome.

"dependencies": {
    "chromedriver": "^106.0.1",
    "selenium-webdriver": "^4.1.1"
  },
 
 -- Google Chrome version.
 
![image](https://user-images.githubusercontent.com/66818290/196542014-d54f3b3e-3f36-4bc8-b8ad-595a6338f972.png)

-- Error running start or test script.

![image](https://user-images.githubusercontent.com/66818290/196542246-b78bf385-d990-4cf9-beb6-009976c86c9e.png)

Additional: I think that chrome driver is not recognized

**Comment by jrichardsz** [comment]
fixed
