### ISSUE TITLE
test: npx isn't working in linux

### ISSUE THREAD

**Issue by AJ-Derteano** [usil/selenium-nodejs-starter#9]
When running the project (npm run test), it does not recognize the npx command:
![Failed to execute](https://user-images.githubusercontent.com/55628495/196559663-e9e5aa2d-952d-4fe4-bd83-5c2c6ebbce6c.png)

This is run from ./src/index.js : 147
![execution code](https://user-images.githubusercontent.com/55628495/196560307-bd6eb1ae-e4fe-45d3-98a8-6641d74235ee.png)

**Comment by jrichardsz** [comment]
fixed
